### PR TITLE
chore(typings): Add "intervalNum" property

### PR DESCRIPTION
**Pull request by bennyn**
Sample payload for `rateLimits` is:

```json
  "rateLimits": [
    {
      "rateLimitType": "REQUEST_WEIGHT",
      "interval": "MINUTE",
      "intervalNum": 1,
      "limit": 1200
    },
    {
      "rateLimitType": "ORDERS",
      "interval": "SECOND",
      "intervalNum": 1,
      "limit": 10
    },
    {
      "rateLimitType": "ORDERS",
      "interval": "DAY",
      "intervalNum": 1,
      "limit": 100000
    }
  ]
```

### CODE REVIEW

**Comment by balthazar** [comment]
Thanks! Btw I think your profile picture got hacked by a marmot

**Comment by bennyn** [comment]
Hihi, marmots are very possessive! Can you make a new release version with the new types? I need them because otherwise my application won't compile. 🥴

**Comment by balthazar** [comment]
Done!

**Comment by bennyn** [comment]
Thank you!! 😊

**Pull request merged**
