### PR TITLE
fix issue header Sec-WebSocket-Protocol was null

### PR DESCRIPTION
**Pull request by maxinminax**
https://github.com/HyperCubeProject/binance-api-node/issues/68

### CODE REVIEW

**Comment by balthazar** [comment]
Are you sure changing `null` to `undefined` would fix the issue? `null` is actually what's specified in their README. Would an empty array work? I think it would make more sense

**Comment by balthazar** [comment]
@bennyn Any thoughts on that?

**Comment by bennyn** [comment]
I am okay with `undefined` instead of `null` because that's like it is recommended by the reconnecting-websocket documentation: https://github.com/pladaria/reconnecting-websocket/tree/v3.2.1#max-retries

I also used the `undefined` value [in my initial PR](https://github.com/HyperCubeProject/binance-api-node/pull/49#discussion_r172299704).

**Comment by balthazar** [comment]
Alright thanks!

**Pull request merged**
