### PR TITLE
Rename `type` for execution report to `eventType`

### PR DESCRIPTION
**Pull request by vilic**

### CODE REVIEW

**Comment by balthazar** [comment]
Hello! Thanks! Just to confirm, is this because you prefer naming it `eventType` or is it a convention of binance?

**Comment by vilic** [comment]
@balthazar Hi, I thought it was a mistake as all other objects have the field `eventType` instead of `type`.

**Comment by balthazar** [comment]
Oh yeah, and I'm actually using `eventType` for other events so it's good, thanks! 🙂

**Comment by balthazar** [comment]
Fixed deployed in `0.3.1`

**Pull request merged**
