### PR TITLE
Added .npmignore

### PR DESCRIPTION
**Pull request by shadow1349**
Fixing issue: https://github.com/HyperCubeProject/binance-api-node/issues/177

### CODE REVIEW

**Comment by balthazar** [comment]
Rather than a lengthy npmignore, I'd rather use the `files` properties of the `package.json`

**Comment by shadow1349** [comment]
@balthazar either way, you've got to ignore the .git folder because you can't install or update packages when npm thinks a package is a git repo.

**Comment by balthazar** [comment]
What I am saying is either redo your PR using the files prop or wait for me to get time to do it.

**Comment by jsappme** [comment]
little update on this would be nice please

**Comment by shadow1349** [comment]
@jsappme sorry, got bogged down with work

**Pull request closed without merging**
